branches:
  only:
    - master

image:
  - Visual Studio 2015
# - Ubuntu1804

# environment:
#   matrix:
#     # Visual Studio
#     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#       PROJECT_DIR: vs2015

configuration: Release

only_commits:
  message: /build/

# build:
#   project: CMakeLists.txt

build: off

#----------------------------------------------------------------------

# For Ubuntu
#   cmake build release
#   embed version number?
#
# For Windows
#   msbuild release version
#   run tests

before_build:
  cmd: |
    echo xx before build

build_script:
  sh: |
    mkdir build
    cd build
    cmake --version
    cmake ..
    cmake --build .
  cmd: |
    echo xx build script
    C:\\Python37\\python.exe update_version.py %APPVEYOR_BUILD_VERSION%
    echo xx after python
    msbuild cd_deluxe_vs2015.sln /property:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    Release\\testmain.exe
    chdir install
    makensis.exe cdd_installer.nsi
    appveyor PushArtifact *.exe -DeploymentName cdd_artifact

after_build:
  cmd: |
    echo xx after build

test_script:
  sh: |
    test/testmain
  cmd: |
    Release\\testmain.exe

# vim:sw=2:ts=2:et
