branches:
  only:
    - master

image:
#  - Visual Studio 2015
  - Ubuntu1804

# environment:
#   matrix:
#     # Visual Studio
#     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#       PROJECT_DIR: vs2015

configuration: Release

skip_tags: true

only_commits:
  message: /build/

# build:
#   project: CMakeLists.txt

#----------------------------------------------------------------------

# For Ubuntu
#   cmake build release
#   embed version number?
#
# For Windows
#   msbuild release version
#   run tests

before_build:
  cmd: |
    echo xx before build

build_script:
  - cmd: |
      echo xx build_script cmd start
      C:\\Python37\\python.exe update_version.py %APPVEYOR_BUILD_VERSION%
      echo xx after python
      msbuild cd_deluxe_vs2015.sln /property:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      Release\\testmain.exe
      chdir install
      makensis.exe cdd_installer.nsi
      dir/b *.exe > name_exe.tmp
      set/p name_exe=< name_exe.tmp
      appveyor PushArtifact %name_exe% -DeploymentName cdd_artifact
      echo xx build_script cmd finish
  - sh: |
      echo xx build_script sh start
      python3 update_version.py ${APPVEYOR_BUILD_VERSION}
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release ..
      cmake --build .
      test/testmain
      release_name=cdd-v${APPVEYOR_BUILD_VERSION}
      mkdir ${release_name}
      cp main/_cdd ${release_name}
      cp ../LICENSE ${release_name}
      cp ../install_ubuntu/INSTALL ${release_name}
      artifact_name=${release_name}.tgz
      tar -zcvf ${artifact_name} ${release_name}
      ll ${artifact_name}
      tar -ztvf ${artifact_name}
      appveyor PushArtifact ${artifact_name} -DeploymentName cdd_artifact
      echo xx build_script sh finish

#   sh: |
#     mkdir build
#     cd build
#     cmake --version
#     cmake ..
#     cmake --build .
#   cmd: |
#     echo xx build script
#     C:\\Python37\\python.exe update_version.py %APPVEYOR_BUILD_VERSION%
#     echo xx after python
#     msbuild cd_deluxe_vs2015.sln /property:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#     Release\\testmain.exe
#     chdir install
#     makensis.exe cdd_installer.nsi
#     appveyor PushArtifact *.exe -DeploymentName cdd_artifact

after_build:
  - cmd: |
      echo xx after build cmd
  - sh: |
      echo xx after build sh

# test_script:
#   sh: |
#     test/testmain
#   cmd: |
#     Release\\testmain.exe

deploy:
  - provider: GitHub
    description: 'MG github deploy'
    artifact: cdd_artifact
    auth_token:
      secure: 2agopPPVSs1AmZL7j9rh7Sr1msI3hKGjAkuTezGgEgsCvoaWTDdpp0zUl37McW6d
    on:
      branch: master

# vim:sw=2:ts=2:et
